model_list:
  - model_name: gemma3
    litellm_params:
      model: openai/gpt-4o
      api_base: http://192.168.11.80:8000/v1
      api_key: dummy
      custom_llm_provider: openai
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: "os.environ/OPENAI_API_KEY"
litellm_settings:
  logging: True