apiVersion: v1
kind: Service
metadata:
  name: litellm-service
  labels:
    app: litellm
spec:
  type: LoadBalancer
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000